# 应用服务 WEB 访问端口
server:
  port: 8063
# 应用名称
spring:
  application:
    name: health-member
  #spring.cloud.nacos.discovery.server-addr=127.0.0.1:8845
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host2}:3406/health_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: ${host1}:8848
    sentinel:
      transport:
        dashboard: ${host1}:9990
  rabbitmq:
    host: ${host2}
    virtual-host: /
    port: 5672
    # 生产端确认回调
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: auto
    username: itcast
    password: 123
# 微信解密数据的相关配置 dsfs sxc
# 龙凯
wx:
  url: api.weixin.qq.com/sns/jscode2session
  appid: wxdb1eedc659cc3e1e
  secret: 68da3d59db125358c5826c64796943ed
  grant_type: authorization_code
# 涣锋
#wx:
#  url: api.weixin.qq.com/sns/jscode2session
#  appid: wxffd8f31f5bb7f05f
#  secret: baa7959cdd43af09c9c5bcb0d3e426ea
#  grant_type: authorization_code
# 发送微信http请求的
httppool:
  max_total: 200
  max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

# 分布式事务
seata:
  registry:
    type: nacos
    nacos: # tc的地址
      # 如何在注册中心找到一个服务：namespce->group->service->cluster
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-tc-server
      # 还差个集群名称：根据下面的事务组找映射关系，再找到集群名称
  tx-service-group: seata-demo  # 事务组，根据这个获取tc服务的cluster名称  （有什么用：想要被tc管理就得在同个事务组内，可用于集群容错）
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      seata-demo: DG
  data-source-proxy-mode: AT



